name: GitHub Actions

on: [push]

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            build_type: "Release", cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
    steps:
    - uses: actions/checkout@v3
    
    - name: git fetch
      run: git fetch --unshallow --update-head-ok origin '+refs/heads/*:refs/heads/*'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: "6.4.0"
        target: 'desktop'
        install-deps: 'true'
          
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: $env{QT6_DIR}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
